export ANDROID_LIB_NAME="test-game"
export IOS_CARGO_PROFILE="release"
export PROJECT_NAME="TestGame"
export APP_NAME="test-game"
#export CARGO_PROFILE_FOR_PROFILING="release"
export CARGO_PROFILE_FOR_PROFILING="dev"
