export ANDROID_LIB_NAME="test-game"
export IOS_SIMULATOR_SCHEME="TestGame Simulator"
export IOS_RELEASE_SCHEME="TestGame"
export IOS_CARGO_PROFILE="release"
export PROJECT_NAME="TestGame"
export APP_NAME="test-game"
