[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "dispatch"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "dispatch"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }

gm = { workspace = true }
refs = { workspace = true }
