[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "dispatch"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "dispatch"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }

gm = { workspace = true }
refs = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = { workspace = true }
pollster = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[build-dependencies]
plat = { workspace = true }
