[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "dispatch"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "dispatch"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }

gm = { workspace = true }
refs = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
gloo-timers = { version = "0.3", features = ["futures"] }

[build-dependencies]
plat = { workspace = true }