[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "gm"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "gm"

[dependencies]
arbitrary = { workspace = true }
bytemuck = { workspace = true }
chrono = { workspace = true }
educe = { workspace = true }
fastrand = { workspace = true }
lyon = { workspace = true }
serde = { workspace = true }
