[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "audio"

[lib]
crate-type = ["rlib", "staticlib"]
name = "audio"

[dependencies]
log = { workspace = true }
manage = { workspace = true }

rodio = { workspace = true }

[build-dependencies]
plat = { workspace = true }
