[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "audio"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "audio"

[features]
defaut = []
disabled = []

[dependencies]
log = { workspace = true }

#rodio = { workspace = true, optional = true }

refs = { workspace = true }

[build-dependencies]
plat = { workspace = true }
