[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "game"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "game"

[dependencies]
gm = { workspace = true }
refs = { workspace = true }
window = { workspace = true }
