[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "generate"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "generate"

[dependencies]
contour = { version = "0.12", features = ["f32"] }
fastrand = { workspace = true }
noise = "0.8"

gm = { workspace = true }
