[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "generate"

[lib]
crate-type = ["rlib", "staticlib"]
name = "generate"

[dependencies]
contour = { version = "0.12", features = ["f32"] }
noise = "0.8"

fake = { workspace = true }

gm = { workspace = true }
