[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "scene"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "scene"

[dependencies]
cgmath = { workspace = true }
gm = { workspace = true }
