[package]
edition.workspace = true
name = "store"
version.workspace = true

[dependencies]
#aes-gcm = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

plat = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[build-dependencies]
plat = { workspace = true }
