name: Typos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  typos:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Lint
        run: make lint
